security:
    password_hashers:
        App\Entity\CrmUser:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\CrmUser
                property: user

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login_check
                username_path: user
                password_path: pass
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~
            entry_point: jwt

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/userCreate, roles: PUBLIC_ACCESS }  # <-- AJOUTEZ CETTE LIGNE
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }